spring:
  http:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  datasource:
      username: root
      password:
      driver-class-name: net.sf.log4jdbc.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/baike?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong&strictUpdates=false&autoReconnect=true
      initialSize: 5
      minIdle: 1
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 200000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true

server:
  port: 6395
mybatis:
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql